/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import bajasayu.Conectar;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author cesar
 */
public class formularioAltasAgregar extends javax.swing.JFrame
{

    Conectar enlace = new Conectar();
    Connection co = enlace.conectar();
    private Connection con;
    private Conectar conectar;

    String edad = null, nombre = null, ltaAnio = null, bajaAnio = null,
            fn = null, ac = null, ine = null, recidencia = null,
            curp = null, rfc = null, constanciaDomiciliaria = null,
            cartillaMilitar = null, gradoEstudios = null, licenciaturaOficio = null,
            tituloProfesional = null, cedulaProfesional = null,
            actualizacionesCertificacion = null, certificadoAntecedentes = null,
            CertificadoMedico = null, cartaRecomendacion = null, numIsse = null,
            constanciaValidez = null, bajaIssem = null;

    String s = String.valueOf(Altas.filaAltas + 1);

    String ultimonumero = "";
    public int ultimoNumeroInt = 0;

    int cont = 0;
    int contCurp = 0;
    int contRFC = 0;
    public static int filaB = Altas.filaAltas + 1;

    public formularioAltasAgregar()
    {
        initComponents();
        setLocationRelativeTo(null);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;

        mostar();
        conectar = new Conectar();
    }

    public DefaultComboBoxModel obtener(String v1, String v2, String v3)
    {
        DefaultComboBoxModel valor = new DefaultComboBoxModel();
        valor.addElement(v1);
        valor.addElement(v2);
        valor.addElement(v3);

        return valor;
    }

    public DefaultComboBoxModel obtenerModificar(String v1)
    {
        DefaultComboBoxModel valor = new DefaultComboBoxModel();
        valor.addElement(v1);
        return valor;
    }

    public void mostar()
    {
        DefaultComboBoxModel valor = new DefaultComboBoxModel();
        //pasa el numero del empleado

        // buscar por numero
        String[] datos = new String[22];
        // banderas de datos en combobox
        boolean si = false;
        boolean no = false;
        boolean falta = false;
        int ban = 0;
        try
        {
            Statement leer = co.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT numEmpleado FROM altas ");
            if ((resultado.equals(null) || resultado.equals("") || resultado.equals(" ")))
            {
                ban = 1;
            } else
            {
                while (resultado.next())
                {
                    if (resultado.last())
                    {
                        datos[0] = resultado.getString(1);//ultimo numero de empleado en la base
                    }
                }

            }

        } catch (SQLException e)
        {
            System.out.println("error de e " + e);
        }
        System.out.println("datos[0] " + datos[0]);
        if (datos[0] != null)
        {
            ultimoNumeroInt = Integer.parseInt(datos[0]);
            ultimoNumeroInt++;
            ultimonumero = String.valueOf(ultimoNumeroInt);
            lbLista.setText(ultimonumero);
        } else
        {
            int cero = 0;
            ultimoNumeroInt = cero;
            ultimoNumeroInt++;
            ultimonumero = String.valueOf(ultimoNumeroInt);
            lbLista.setText(ultimonumero);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbLista = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dcAlta = new com.toedter.calendar.JDateChooser();
        dcN = new com.toedter.calendar.JDateChooser();
        dcAltatxt = new javax.swing.JTextField();
        dcNtxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtLO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNoIsse = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtReci = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtGEs = new javax.swing.JTextField();
        txtCURP = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        cbCD = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbAN = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbINE = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        lbmilitar = new javax.swing.JLabel();
        cbCMil = new javax.swing.JComboBox<>();
        lbtp = new javax.swing.JLabel();
        cbTp = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbCP = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbAC = new javax.swing.JComboBox<>();
        jlcap1 = new javax.swing.JLabel();
        jlcap2 = new javax.swing.JLabel();
        cbCANP = new javax.swing.JComboBox<>();
        jlcm = new javax.swing.JLabel();
        cbCM = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cbCR = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cbCV = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel19.setText("Agregar empleado");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 320, 30));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 30));

        jLabel22.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel22.setText("N. Lista");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        lbLista.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        lbLista.setText("0000");
        jPanel3.add(lbLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 70, 20));

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 370, 30));

        jLabel31.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel31.setText("Edad");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 30));

        txtEdad.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel3.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 173, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 190));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel23.setText("Fecha Alta");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 140, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel6.setText("Fecha Nacimiento");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 20));

        dcAlta.setDateFormatString("yyyy-MM-dd");
        dcAlta.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                dcAltaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                dcAltaMouseEntered(evt);
            }
        });
        dcAlta.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                dcAltaPropertyChange(evt);
            }
        });
        jPanel4.add(dcAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 30, 30));

        dcN.setDateFormatString("yyyy-MM-dd");
        dcN.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                dcNPropertyChange(evt);
            }
        });
        jPanel4.add(dcN, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 30, 31));

        dcAltatxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dcAltatxt.setForeground(new java.awt.Color(51, 51, 55));
        dcAltatxt.setText("cdsdcsdc");
        jPanel4.add(dcAltatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, 30));

        dcNtxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dcNtxt.setForeground(new java.awt.Color(51, 51, 55));
        dcNtxt.setText("cdsdcsdc");
        jPanel4.add(dcNtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 380, 270));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jPanel5KeyPressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLO.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtLO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtLOActionPerformed(evt);
            }
        });
        txtLO.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtLOKeyTyped(evt);
            }
        });
        jPanel5.add(txtLO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 390, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel7.setText("Licenciatura / Oficio");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 190, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel20.setText("No. ISSEMYM");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 30));

        txtNoIsse.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtNoIsse.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtNoIsseKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNoIsseKeyTyped(evt);
            }
        });
        jPanel5.add(txtNoIsse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 390, 30));

        jLabel25.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel25.setText("Recidencia");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 20));

        txtReci.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtReci.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtReciKeyTyped(evt);
            }
        });
        jPanel5.add(txtReci, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 440, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel26.setText("CURP");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        txtRFC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRFC.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtRFCKeyTyped(evt);
            }
        });
        jPanel5.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 440, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel27.setText("RFC");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 30));

        jLabel30.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel30.setText("Grado De Estudios");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 30));

        txtGEs.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtGEs.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtGEsKeyTyped(evt);
            }
        });
        jPanel5.add(txtGEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 390, -1));

        txtCURP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCURP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtCURPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtCURPKeyTyped(evt);
            }
        });
        jPanel5.add(txtCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 440, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 590, 300));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel28.setText("Constancia Domiciliaria");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 30));

        cbCD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbCD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "Falta" }));
        jPanel6.add(cbCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 150, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel10.setText("Acta De Nacimiento");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 20));

        cbAN.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "Falta" }));
        jPanel6.add(cbAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 150, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel12.setText("INE");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 20));

        cbINE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbINE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "Falta" }));
        jPanel6.add(cbINE, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 150, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 590, 160));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbmilitar.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbmilitar.setText("Cartilla Militar");
        jPanel7.add(lbmilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 30));

        cbCMil.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbCMil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "Falta" }));
        jPanel7.add(cbCMil, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 160, 20));

        lbtp.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbtp.setText("Titulo Profesional");
        jPanel7.add(lbtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, 30));

        cbTp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbTp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "Falta", "n/a" }));
        jPanel7.add(cbTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 160, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setText("Cedula Profesional");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 30));

        cbCP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbCP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "Falta", "n/a" }));
        cbCP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbCPActionPerformed(evt);
            }
        });
        jPanel7.add(cbCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 160, 20));

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel14.setText("Actualizaciones Certificación");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 250, 30));

        cbAC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbAC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "Falta", "n/a", "Certificado" }));
        jPanel7.add(cbAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 160, 20));

        jlcap1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jlcap1.setText("Certificado Antecedentes");
        jPanel7.add(jlcap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 230, 30));

        jlcap2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jlcap2.setText("no Penales");
        jPanel7.add(jlcap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 100, 30));

        cbCANP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbCANP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "Falta", "n/a", "varias", "ninguna", "Diplomado mejora", "informe", "publica" }));
        jPanel7.add(cbCANP, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 130, -1));

        jlcm.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jlcm.setText("Certificado Medico");
        jPanel7.add(jlcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 170, 30));

        cbCM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbCM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "Falta", "n/a", "certificado", "informe" }));
        jPanel7.add(cbCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 130, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel17.setText("Carta de Recomendación");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 220, 30));

        cbCR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbCR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "Falta", "n/a", "pendiente" }));
        jPanel7.add(cbCR, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 130, 30));

        jLabel21.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel21.setText("Constancia de validez");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 200, 30));

        cbCV.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "Falta", "n/a", "No" }));
        jPanel7.add(cbCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 130, 30));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 990, 190));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar64p.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel8.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 70));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Agregar");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 30));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, -10, 150, 170));
        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1190, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // Boton de regreso a la tabla de altas

        formularioAltasAgregar fa = new formularioAltasAgregar();
        fa.setVisible(false);
        super.dispose();
        Altas a = new Altas();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        PreparedStatement ps;
        String sql;
        String nombre = txtNombre.getText();
        String fechaAlta = dcAltatxt.getText();

        String fechaN = dcNtxt.getText();

        String acta = (String) cbAN.getSelectedItem();
        String ine = (String) cbINE.getSelectedItem();
        String constancia = (String) cbCD.getSelectedItem();
        String tituloP = (String) cbTp.getSelectedItem();
        String cedula = (String) cbCP.getSelectedItem();
        String actu = (String) cbAC.getSelectedItem();
        String anp = (String) cbCANP.getSelectedItem();
        String medico = (String) cbCM.getSelectedItem();
        String carta = (String) cbCR.getSelectedItem();
        String validez = (String) cbCV.getSelectedItem();
        String cartilla = (String) cbCMil.getSelectedItem();

        String recidencia = txtReci.getText();
        String curp = txtCURP.getText();
        String rfc = txtRFC.getText();
        String grado = txtGEs.getText();
        String numI = txtNoIsse.getText();
        String li = txtLO.getText();
        String edad = txtEdad.getText();

        PreparedStatement pps;
        DefaultComboBoxModel valor = new DefaultComboBoxModel();
        try
        {
            if (nombre.equals(null) || nombre.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Debe ingresar un nombre");

            } else
            {
                if (fechaAlta.equals(null) || fechaAlta.equals(""))
                {
                    JOptionPane.showMessageDialog(null, "La fecha de alta debe contener algo");
                } else
                {

                    if (fechaN.equals(null) || fechaN.equals(""))
                    {
                        JOptionPane.showMessageDialog(null, "La fecha de nacimento debe contener algo");
                    } else
                    {

                        if (recidencia.equals(null) | recidencia.equals(""))
                        {
                            JOptionPane.showMessageDialog(null, "la recidencia debe contener algo ");
                        } else
                        {
                            if (curp.equals(null) || curp.equals(""))
                            {
                                JOptionPane.showMessageDialog(null, "Debe poner algo en la curp");
                            } else
                            {
                                if (rfc.equals(null) || rfc.equals(""))
                                {
                                    JOptionPane.showMessageDialog(null, "Debe ingresar algo en el RFC");
                                } else
                                {
                                    if (grado.equals(null) || grado.equals(""))
                                    {
                                        JOptionPane.showMessageDialog(null, "Debe ingresar algo en el grado de estudios");
                                    } else
                                    {
                                        if (numI.equals(null) || numI.equals(""))
                                        {
                                            JOptionPane.showMessageDialog(null, "Debe ingresar algo en el número de Issemin");
                                        } else
                                        {
                                            if (li.equals(null) || li.equals(""))
                                            {
                                                JOptionPane.showMessageDialog(null, " debe ingresar algo en la licenciatura u oficio");
                                            } else
                                            {
                                                if (edad.equals(null) || edad.equals(""))
                                                {
                                                    JOptionPane.showMessageDialog(null, "Debe ingresar una edad");
                                                } else
                                                {
                                                    con = conectar.conectar();
                                                    sql = "insert into altas (numEmpleado, nommbre, altaAnio, edad, fechaNacimiento, actaNacimiento, ine, recidencia, CURP, RFC, constanciaDomiciliaria,cartillaMilitar, gradoEstudios, licenciaturaOficio, tituloProfesional, cedulaProfesional,actualizacionesCertificacion, certificadoAntecedentesNoPenales, certificadoMedico, cartaRecomendacion, numIssemym, constanciaValidez) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
                                                    ps = con.prepareStatement(sql);

                                                    ps.setInt(1, ultimoNumeroInt);
                                                    ps.setString(2, nombre);
                                                    ps.setString(3, fechaAlta);

                                                    ps.setString(4, edad);
                                                    ps.setString(5, fechaN);
                                                    ps.setString(6, acta);
                                                    ps.setString(7, ine);
                                                    ps.setString(8, recidencia);
                                                    ps.setString(9, curp);
                                                    ps.setString(10, rfc);
                                                    ps.setString(11, constancia);
                                                    ps.setString(12, cartilla);
                                                    ps.setString(13, grado);
                                                    ps.setString(14, li);
                                                    ps.setString(15, tituloP);
                                                    ps.setString(16, cedula);
                                                    ps.setString(17, actu);
                                                    ps.setString(18, anp);
                                                    ps.setString(19, medico);
                                                    ps.setString(20, carta);
                                                    ps.setString(21, numI);
                                                    ps.setString(22, validez);

                                                    int valorRetorno = JOptionPane.showConfirmDialog(null,
                                                        "¿Quiere agregar a un empleado en las Altas?",
                                                        "Agregar",
                                                        JOptionPane.YES_NO_OPTION);

                                                    if (valorRetorno == 0)
                                                    {
                                                        ps.executeUpdate();
                                                        JOptionPane.showMessageDialog(null, "se agrego a un empleado en las altas ");
                                                        super.dispose();
                                                        Altas a = new Altas();
                                                        a.setVisible(true);
                                                    } else
                                                    {
                                                        if (valorRetorno == 1)
                                                        {
                                                            JOptionPane.showMessageDialog(null, "No se agrego ningun empleado las altas");
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

                }
            }
        } catch (SQLException ex)
        {
            System.out.println("error de " + ex);
        }
        super.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cbCPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbCPActionPerformed
    {//GEN-HEADEREND:event_cbCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCPActionPerformed

    private void jPanel5KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPanel5KeyPressed
    {//GEN-HEADEREND:event_jPanel5KeyPressed
        char validar = evt.getKeyChar();
        char val = validar;
        if (Character.isAlphabetic(validar))
        {
        } else
        {
            if (val == ' ')
            {

            } else
            {
                System.out.println("validaresp " + val);
                getToolkit().beep();
                evt.consume();
            }
        }

        if (Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jPanel5KeyPressed

    private void txtCURPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCURPKeyTyped
    {//GEN-HEADEREND:event_txtCURPKeyTyped
        char validar = evt.getKeyChar();
        char val = validar;

        if (contCurp < 0)
        {
            contCurp = 0;
        }
        if (val == 8)
        {

            contCurp--;

        }
        if (contCurp == 18)
        {
            JOptionPane.showMessageDialog(this, "solo puede escribir 18 caracteres");
            getToolkit().beep();
            evt.consume();
        } else
        {
            if (val == 8)
            {
                System.out.println("val " + val);
                //contCurp--;
                System.out.println("con " + contCurp);
            } else
            {
                contCurp++;
            }
        }
    }//GEN-LAST:event_txtCURPKeyTyped

    private void txtCURPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCURPKeyPressed
    {//GEN-HEADEREND:event_txtCURPKeyPressed

    }//GEN-LAST:event_txtCURPKeyPressed

    private void txtGEsKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtGEsKeyTyped
    {//GEN-HEADEREND:event_txtGEsKeyTyped
        char validar = evt.getKeyChar();
        char val = validar;
        if (Character.isAlphabetic(validar))
        {
        } else
        {
            if (val == ' ')
            {

            } else
            {
                getToolkit().beep();
                evt.consume();
            }
        }

        if (Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtGEsKeyTyped

    private void txtRFCKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtRFCKeyTyped
    {//GEN-HEADEREND:event_txtRFCKeyTyped
        char validar = evt.getKeyChar();
        char val = validar;

        if (contRFC < 0)
        {
            contRFC = 0;
        }
        if (val == 8)
        {

            contRFC--;

        }
        if (contRFC == 13)
        {
            JOptionPane.showMessageDialog(this, "solo puede escribir 13 caracteres");
            getToolkit().beep();
            evt.consume();
        } else
        {
            if (val == 8)
            {
                System.out.println("val " + val);

                System.out.println("con " + contCurp);
            } else
            {
                contRFC++;
            }
        }
    }//GEN-LAST:event_txtRFCKeyTyped

    private void txtReciKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtReciKeyTyped
    {//GEN-HEADEREND:event_txtReciKeyTyped
        char validar = evt.getKeyChar();
        char val = validar;
        if (Character.isAlphabetic(validar))
        {
        } else
        {
            if (val == ' ')
            {

            } else
            {
                getToolkit().beep();
                evt.consume();
            }
        }

        if (Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtReciKeyTyped

    private void txtNoIsseKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNoIsseKeyTyped
    {//GEN-HEADEREND:event_txtNoIsseKeyTyped
        char validar = evt.getKeyChar();
        char val = validar;

        if (!Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNoIsseKeyTyped

    private void txtNoIsseKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNoIsseKeyPressed
    {//GEN-HEADEREND:event_txtNoIsseKeyPressed

    }//GEN-LAST:event_txtNoIsseKeyPressed

    private void txtLOKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtLOKeyTyped
    {//GEN-HEADEREND:event_txtLOKeyTyped
        char validar = evt.getKeyChar();
        char val = validar;
        if (Character.isAlphabetic(validar))
        {
        } else
        {
            if (val == ' ')
            {

            } else
            {
                getToolkit().beep();
                evt.consume();
            }
        }

        if (Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtLOKeyTyped

    private void txtLOActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtLOActionPerformed
    {//GEN-HEADEREND:event_txtLOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLOActionPerformed

    private void dcNPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_dcNPropertyChange
    {//GEN-HEADEREND:event_dcNPropertyChange
        String seleccion = ((JTextField) dcN.getDateEditor().getUiComponent()).getText();
        dcNtxt.setText(seleccion);
    }//GEN-LAST:event_dcNPropertyChange

    private void dcAltaPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_dcAltaPropertyChange
    {//GEN-HEADEREND:event_dcAltaPropertyChange

        String seleccion = ((JTextField) dcAlta.getDateEditor().getUiComponent()).getText();
        dcAltatxt.setText(seleccion);
    }//GEN-LAST:event_dcAltaPropertyChange

    private void dcAltaMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_dcAltaMouseEntered
    {//GEN-HEADEREND:event_dcAltaMouseEntered

    }//GEN-LAST:event_dcAltaMouseEntered

    private void dcAltaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_dcAltaMouseClicked
    {//GEN-HEADEREND:event_dcAltaMouseClicked

    }//GEN-LAST:event_dcAltaMouseClicked

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtEdadKeyTyped
    {//GEN-HEADEREND:event_txtEdadKeyTyped
        char validar = evt.getKeyChar();
        char val = validar;

        if (cont < 0)
        {
            cont = 0;
        }
        if (val == 8)
        {
            cont--;
        }
        if (cont == 2)
        {
            JOptionPane.showMessageDialog(this, "solo puede escribir una edad de dos numeros");
            getToolkit().beep();
            evt.consume();
        } else
        {
            if (Character.isDigit(validar))
            {
                cont++;
                System.out.println("digitos " + cont);
            } else
            {
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombreKeyTyped
    {//GEN-HEADEREND:event_txtNombreKeyTyped
        char validar = evt.getKeyChar();
        char val = validar;
        if (Character.isAlphabetic(validar))
        {
        } else
        {
            if (val == ' ')
            {

            } else
            {
                System.out.println("validaresp " + val);
                getToolkit().beep();
                evt.consume();
            }
        }

        if (Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(formularioAltasAgregar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(formularioAltasAgregar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(formularioAltasAgregar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(formularioAltasAgregar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new formularioAltasAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbAC;
    private javax.swing.JComboBox<String> cbAN;
    private javax.swing.JComboBox<String> cbCANP;
    private javax.swing.JComboBox<String> cbCD;
    private javax.swing.JComboBox<String> cbCM;
    private javax.swing.JComboBox<String> cbCMil;
    private javax.swing.JComboBox<String> cbCP;
    private javax.swing.JComboBox<String> cbCR;
    private javax.swing.JComboBox<String> cbCV;
    private javax.swing.JComboBox<String> cbINE;
    private javax.swing.JComboBox<String> cbTp;
    private com.toedter.calendar.JDateChooser dcAlta;
    private javax.swing.JTextField dcAltatxt;
    private com.toedter.calendar.JDateChooser dcN;
    private javax.swing.JTextField dcNtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlcap1;
    private javax.swing.JLabel jlcap2;
    private javax.swing.JLabel jlcm;
    private javax.swing.JLabel lbLista;
    private javax.swing.JLabel lbmilitar;
    private javax.swing.JLabel lbtp;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGEs;
    private javax.swing.JTextField txtLO;
    private javax.swing.JTextField txtNoIsse;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtReci;
    // End of variables declaration//GEN-END:variables
}
